Feature/password reset verification code input
PetJournal/petjournal.web pull request #12
Opened 2023-05-08 22:45 UTC by mateuscarvalhodev

## descrição

- pagina para recuperação de senha, onde o usuário recebe um código para recuperar a senha

## validação

- O campo contém apenas números, e o botão fica desabilitdo até todos os inputs serem preenchidos!

2023-05-19 12:23 UTC, larissaOliveiraz submitted a review, later dismissed

2023-05-24 11:30 UTC, leottx requested changes
Comentei no arquivo recoveryCode.tsx um ajuste simples que precisa ser feito.

2023-05-24 11:30 UTC, leottx commented on src/pages/recoveryCode.tsx
Nos nomes das rotas estamos utilizando a convenção `kebab-case`. Todas as letras são minúsculas, sem caracteres especiais e palavras separadas por hífen.

Altera o nome desse arquivo pra `recovery-code.tsx`

2023-07-03 14:40 UTC, whyleonardo approved these changes, later dismissed

2023-07-03 22:20 UTC, brenomorp submitted a review, later dismissed

2023-07-03 22:59 UTC, whyleonardo approved these changes

2023-07-03 22:59 UTC, whyleonardo submitted a review, later dismissed

2023-07-04 02:26 UTC, whyleonardo approved these changes

2023-07-04 02:29 UTC, whyleonardo approved these changes

2023-07-10 22:07 UTC, medeirosdev approved these changes

2023-07-10 22:13 UTC, merged