Feature/species default screen
PetJournal/petjournal.web pull request #23
Opened 2023-07-31 02:56 UTC by brenomorp

## Descrição
Implementação da tela padrão de seleção de espécies, onde o usuário tem a opção de selecionar uma das espécies de animais já existentes ou adicionar uma nova.

## Dependências
Biblioteca Zod para validação do input.

## Validação
Quando o usuário estiver na tela de Espécies, deverá aparecer a mensagem: 

` “Olá (1º Nome do usuário), gostaríamos de saber qual a espécie do seu Pet:”
`

- Na mensagem, o Nome do Usuário é variável, e deve ser preenchido conforme respondido pelo usuário da página de cadastro, no campo "Nome". 

- Na tela de Espécies, deverá haver 7 opções selecionáveis para o usuário escolher entre as diferentes opções: Cachorro, Pássaro, Gato, Peixe, Réptil, Roedor e Outros... . 

- As opções de espécie devem conter o nome da espécie e uma imagem que represente a espécie.
 
- As opções de espécie devem ficar desabilitadas até que o usuário selecione uma.

- Quando o usuário clilcar em "Outros...", deverá  aparecer um campo digitável para o usuário digitar qual é a espécie do seu pet.

- O usuário só poderá escolher uma opção entre as espécies.

- Se o usuário selecionar uma segunda opção entre as espécies, a primeira seleção deverá ser desabilitada. 

- O usuário não pode escolher uma das opções de espécie e "Outros...".  

- Se o usuário selecionar uma das espécies, e clilcar em "Outros...", automaticamente, a espécie selecionada anteriormente é desabilitada. 

- A seleção de qualquer espécie ou o preenchimento da informação em "Outros" é obrigatória para seguir o fluxo de cadastro. 

- Se o usuário selecionar uma das éspecies, o botão "Continuar" deverá ser habilitado. 

- Se o usuário não escolher entre uma das opções de espécie, mas digitar a éspecie do seu pet no campo digitável, o botão "Continuar" deverá ser habilitado. 

- O campo digitável de "Outros.." , não pode conter menos de 3 caracteres.

- O campo digitável de "Outros.." não pode conter números e nem caracteres especiais.

- Quando usuário clicar em “Continuar”,  deverá ser levado para a página Nome e Gênero

- Deverá conter um botão de "voltar" sempre habilitado, para que o usuário retorne para a página Inicial de Cadastro de Pet

___

OBS.: As partes que necessitam de integração com o backend ou necessitam de integração com alguma outra tela que ainda não foi desenvolvida não foram concluídas

2023-08-02 22:44 UTC, medeirosdev approved these changes
Aprovado bro

2023-08-08 22:14 UTC, priscillatrevizan approved these changes
Approved!

2023-08-18 00:53 UTC, Jeeffsantoos commented
Consertar conflitos dos arquivos de dependencias (yarn.lock)"

fazer a integração com o back!

2023-08-18 01:09 UTC, Jeeffsantoos requested changes
Consertar conflitos dos arquivos de dependencias (yarn.lock)"

fazer a integração com o back!

2023-08-18 01:09 UTC, closed without merging