Create docs for web
PetJournal/petjournal.web pull request #24
Opened 2023-08-02 01:35 UTC by brenomorp

2023-08-02 22:46 UTC, medeirosdev approved these changes, later dismissed
https://github.com/PetJournal/petjournal.web/assets/92064842/7c8b391c-de30-44b4-8e40-405d6e742db3

Aprovado

2023-08-07 22:36 UTC, medeirosdev approved these changes, later dismissed
![image](https://github.com/PetJournal/petjournal.web/assets/92064842/484cbbdd-fa87-43ee-9b62-30f718ea91c8)

2023-08-08 22:02 UTC, priscillatrevizan requested changes
@brenomorp aqui vc colocou npm, antes era usado yarn. Mudou para npm mesmo?

2023-08-09 23:38 UTC, brenomorp commented
> @brenomorp aqui vc colocou npm, antes era usado yarn. Mudou para npm mesmo?

Corrigido. Eu utilizei o npm porque havia tanto yarn quanto npm no projeto. Eu cheguei a comentar no Discord, o Dan disse que seria melhor a gente escolher um e padronizar para o projeto todo.

2023-08-10 12:37 UTC, priscillatrevizan approved these changes
Obgda Breno!! Aprovado :)

2023-08-18 00:32 UTC, Jeeffsantoos approved these changes

2023-08-18 00:32 UTC, merged