refact: zod implamentation login
PetJournal/petjournal.web pull request #25
Opened 2023-08-06 17:50 UTC by priscillatrevizan

refact: zod implamentation login

2023-08-06 22:55 UTC, medeirosdev approved these changes
![image](https://github.com/PetJournal/petjournal.web/assets/92064842/638eb396-cfea-4e8a-8f8f-d760f9c30f69)

2023-08-10 12:39 UTC, priscillatrevizan commented
@brenomorp faz um review pra nós tmb, please..? ☺️

2023-08-18 00:19 UTC, Jeeffsantoos requested changes
Consumir a API que está pronta!

2023-08-18 00:20 UTC, Jeeffsantoos submitted a review, later dismissed

2023-08-18 00:28 UTC, Jeeffsantoos commented
Consumir a API que está pronta!

2023-08-18 00:30 UTC, closed without merging