[PS-227] Feature: Create Input Component
PetJournal/petjournal.web pull request #50
Opened 2024-06-15 19:59 UTC by diogocaxiado

# Pull Request em desenvolvimento:

### 1. Componetização do Input

   - **Criação de um Componente Reutilizável:**
      - Introdução do componente `Input`, que encapsula uma `<div>` com dois elementos filhos:
         - `Label` : Extensão da tag HTML `<label>`. 
         - `Input` : Extensão da tag HTML `<input>`.
         
   - **Tratamento do Tipo Password:**
      - Ao utilizar o parâmetro `type: password`, a funcionalidade de alternar a visibilidade do texto será automaticamente configurada, incluindo um ícone de olho para essa alternância.
      
   - **Variantes de estilo:**
      - `primary`: Estilo com label roxo e borda sólida no input.
         
         ![image](https://github.com/PetJournal/petjournal.web/assets/65976610/2496d413-2d85-48db-8ef4-ec206d38de12)

      - `secondary`: Estilo com label preto e borda tracejada no input.
        
        ![image](https://github.com/PetJournal/petjournal.web/assets/65976610/1c7452e4-89f4-433e-b5eb-21620fca5f13)

   - **Integração com Tailwind CSS:**
       - Utilização de classes do Tailwind CSS para estilização.
       - Combinação dinâmica de classes utilizando `twMerge`.

2024-06-15 20:33 UTC, herisonp requested changes
Bacana demais sua implementação, @diogocaxiado. Deixei algumas observações, para melhorar a reutilização do componente.

2024-06-15 20:33 UTC, herisonp commented on src/components/input.tsx
Nome do arquivo, pode ser exatamente o nome do componente. Então ficaria como "Input.tsx".

2024-06-15 20:33 UTC, herisonp commented on src/components/input.tsx
> +              />
Esse ícone, você pode criar um componente de icone, seguindo o padrão dos demais icones na pasta /icons.

2024-06-15 20:33 UTC, herisonp commented on src/components/input.tsx
> +              className,
Aqui, a gente vai ter um probleminha na reutilização do componente utilizando classes do tailwind. Explico:

Como temos uma `<div>` por fora de tudo, se a gente precisar reposicionar o Input, algo como `<Input className="mt-8" />`, o que vai estar recebendo a estilização de posicionamento, vai ser o elemento `<input />`, então a `<div>`.

Então, pensando nesses tipos de uso, talvez, seja interessante separar o componente Label e o componente de Input. E em cada um, ter apenas suas respectivas tags HTML.

Vou deixar como referência como o shadcn fez, você pode adotar a mesma idéia. https://ui.shadcn.com/docs/components/input

Em resumo:
- Criar um componente de Label (separado em arquivo mesmo)
- Criar o componente de Input, recebendo diretamente apenas o `<input>`, suas variações e utilitários (como mensagens de erros, etc...)

2024-06-15 20:33 UTC, herisonp commented on src/components/input.tsx
> +Label.displayName = 'Label';
Tudo isso aqui num arquivo seprado.

2024-06-15 20:33 UTC, herisonp commented on src/components/input.tsx
> +        </Label>
Deixar a opção de ter label ou não, durante a reutilização.
![image](https://github.com/PetJournal/petjournal.web/assets/6376160/94c002f5-c61d-4126-84c7-7a0578050f20)

2024-06-16 15:12 UTC, diogocaxiado commented on src/components/input.tsx
Acabo de alterar o nome do arquivo do componente.

2024-06-16 15:21 UTC, diogocaxiado commented on src/components/input.tsx
> +              />
- Criação do componente sugerido dentro da pasta `/icons` com o nome `IconInputPassword.tsx`.
- Implementação do componente `IconInputPassword.tsx` dentro do componente `Input.tsx`.

2024-06-16 16:47 UTC, diogocaxiado commented on src/components/input.tsx
> +              className,
- Refatoração do component `Input` com um ternário no retorno do componente, caso utilize o `type = password` irá ser incrementado o ícone dos olhos para esconder e mostrar a senha.
- Criação do componente Label enviado neste [PR](https://github.com/PetJournal/petjournal.web/pull/51)

- Falta a implementação de mensagem de erro no momento

2024-06-16 16:48 UTC, diogocaxiado commented on src/components/input.tsx
> +        </Label>
Imagino que esta mensagem estava relacionada anteriormente quando ainda não havia a divisão dos componentes, correto? Com isso posso desconsiderar?

2024-06-16 21:28 UTC, herisonp commented on src/components/input.tsx
> +        </Label>
@diogocaxiado isso! Pode desconsiderar sim.

2024-06-16 21:56 UTC, herisonp requested changes
@diogocaxiado ficou massa! Separado ficou bem melhor. Testei localmente tbm, e ficou certinho. Só faz essas correções que marquei, que finalizou.

2024-06-16 21:56 UTC, herisonp commented on src/components/Input.tsx
> +        {...props}
Aqui pode passar o ref e as props para o elemento de input.

2024-06-16 21:56 UTC, herisonp commented on src/components/icons/IconInputPassword.tsx
> +      src={active ? toggleShowPassword : toggleHiddenPassword}
Aqui ficou invertido o ícone. Quando o usuário quer exibir a senha, o olhinho tem que ser o normal; e quando ela quiser esconder a senha, o olhinho tem que ser o riscado. Ou seja, o ícone precisa representar a ação que o usuário vai fazer, e não o estado atual.

2024-06-16 23:23 UTC, diogocaxiado commented on src/components/Input.tsx
> +        {...props}
- Movendo os parâmetros `ref` e `...props` para dentro do elemento input.

2024-06-16 23:24 UTC, diogocaxiado commented on src/components/icons/IconInputPassword.tsx
> +      src={active ? toggleShowPassword : toggleHiddenPassword}
- Inversão dos ícones para o comportamento adequado ao usuário.

2024-06-16 23:27 UTC, herisonp approved these changes, later dismissed

2024-06-20 04:11 UTC, herisonp requested changes

2024-06-20 04:11 UTC, herisonp commented on src/components/Inputs/InputControl.tsx
Esse componente não precisa ter os demais componentes dentro dele. pode ser só uma div, vazia mesmo. contendo apenas estilos simples de display, como um flex-col e um gap padrão. Pois dessa forma, vai ficar complexo passar propriedades para os demais componentes internos quando tiver sendo feito a reutilização dele.

Perceba que dessa forma, se você quiser passar propriedade como "onChange" ou "name" para o Input, vai precisar deixar muito complexo a forma de uso.

2024-06-20 04:11 UTC, herisonp commented on src/components/Inputs/Input.tsx
Aqui a gente vai ter alguns possíveis "problemas" de performance. Como é algo mais conceitual, vou te mandar uma mensagem no Discord pra te explicar.

2024-06-20 18:41 UTC, herisonp approved these changes
Aprovado, consagrado. 🤙 Excelente trabalho!! 🤗

2024-06-20 18:43 UTC, merged