Feature/58 create pet list page
PetJournal/petjournal.web pull request #69
Opened 2024-07-09 03:15 UTC by diogocaxiado

## Em Construção...

2024-07-11 17:43 UTC, diogocaxiado commented
Aguardando a finalização do PR do @Luzin7 para utilizar na página o componente breadcrump

2024-07-12 18:53 UTC, herisonp requested changes
Como conversamos em call...

2024-07-12 19:23 UTC, herisonp requested changes

2024-07-12 19:23 UTC, herisonp commented on src/services/deletePet.ts
> +    return data;
retornar como objeto { data }

2024-07-12 19:23 UTC, herisonp commented on src/context/PetsContext.tsx
> +    const deletedPet = await deletePet(pet.id);
aqui desestruturar o retorno com `{ data, error }`.

2024-07-12 21:02 UTC, herisonp approved these changes, later dismissed

2024-07-12 21:28 UTC, herisonp approved these changes, later dismissed

2024-07-12 21:55 UTC, herisonp approved these changes

2024-07-12 21:56 UTC, merged