73 feature erros and validation on forget password page
PetJournal/petjournal.web pull request #74
Opened 2024-07-15 20:48 UTC by diogocaxiado

## Em andamento

2024-07-19 13:19 UTC, Luzin7 requested changes
Tá show! Fiz algumas recomendações e pedi algumas alterações por questão de padrão de projeto mesmo.

2024-07-19 13:19 UTC, Luzin7 commented on src/app/(auth)/change-password/components/ChangePasswordForm.tsx
> +  const { register, handleSubmit, formState: { errors } } = useForm<ChangePasswordType>({
Recomendo trocar o `Type` do `ChangePasswordType` por `Props`, por questão de padrão mesmo.

2024-07-19 13:19 UTC, Luzin7 commented on src/app/(auth)/change-password/components/ChangePasswordForm.tsx
> +  async function handleNewPasswordSubmit({ password, passwordConfirmation }: ChangePasswordType) {
Fiz essa alteração pra mostrar que podemos e devemos abusar da desestruturação. Torna o código mais limpo, legível e mais direto.

2024-07-19 13:19 UTC, Luzin7 commented on src/app/(auth)/waiting-code/components/WaitingCodeForm.tsx
> +  const { control, register, handleSubmit, formState: { errors } } = useForm<WaitingCodeType>({
Tenta deixar esse mais próximo do que ficou o outro arquivo.

2024-07-19 13:19 UTC, Luzin7 commented on src/app/(auth)/waiting-code/components/WaitingCodeForm.tsx
> +  async function handleSubmitCode(data: WaitingCodeType) {
Tenta deixar esse mais próximo do que ficou o outro arquivo.

2024-07-19 17:07 UTC, herisonp requested changes
@diogocaxiado além do que o @Luzin7 comentou, deixei uma observação também.

2024-07-19 17:07 UTC, herisonp commented on src/schemas/ChangePassword.ts
@diogocaxiado aqui acho que pode usar o mesmo schema de senha que o @Luzin7 fez. Pra gente deixar padrão as exigências de senha.

2024-07-19 17:10 UTC, diogocaxiado commented on src/schemas/ChangePassword.ts
Acabei de dar uma olhada vou fazer igual!

2024-07-19 17:17 UTC, diogocaxiado reviewed
Vou realizar a alteração nos demais arquivos alterados!

2024-07-19 17:17 UTC, diogocaxiado commented on src/app/(auth)/change-password/components/ChangePasswordForm.tsx
> +  async function handleNewPasswordSubmit({ password, passwordConfirmation }: ChangePasswordType) {
Compreensivel, valeu pela nota!

2024-07-19 17:39 UTC, herisonp approved these changes, later dismissed

2024-07-23 17:05 UTC, herisonp commented
@diogocaxiado Aproveita que o @Luzin7 ainda não aprovou o PR para fazer a resolução de conflitos. Além disso, eu reparei agora que o Label nos seus formulários estão sem a prop de htmlFor para indicar qual o input que o label pertence.

2024-07-23 21:20 UTC, Luzin7 approved these changes
Show! Aprovado.

2024-07-23 21:20 UTC, merged