[72] Feature: Add validation on login page
PetJournal/petjournal.web pull request #75
Opened 2024-07-18 19:26 UTC by Luzin7

2024-07-19 16:32 UTC, herisonp requested changes
@Luzin7 Excelente trabalho!! Deixei uns comentários só pra reforçar o uso dos componentes globais. Fora isso, muito bom.

2024-07-19 16:32 UTC, herisonp commented on src/schemas/userLogin.ts
> +    .trim(),
@Luzin7 Como esse é o schema do login, acho que a gente não precisa validar se a senha está no padrão. No máximo se tem a quantidade de caracteres. Porque esse tipo de validação para o login pode ser usado como brecha. Ou impedir do usuário logar, caso por algum motivo a senha dele não tenha os padrões exigidos.

2024-07-19 16:32 UTC, herisonp commented on src/app/(auth)/login/components/LoginForm.tsx
Muito bom! Validação linda, formosa, cheirosa...

2024-07-19 16:32 UTC, herisonp commented on src/app/(auth)/register/components/RegisterForm.tsx
> +        )}
@Luzin7 a gente tem um componente para mensagens. @/components/Fields/InputMessage. Acho que da pra reutilizar aqui e em todas as mensagens de validação dos formulários (login e register).

2024-07-19 16:32 UTC, herisonp commented on src/app/(auth)/register/components/RegisterForm.tsx
>          <div className="text-custom-purple text-sm font-medium">Sobrenome</div>
@Luzin7 Temos componente de Label. @/components/Label. Pode reutilizar no register e login.

2024-07-19 16:32 UTC, herisonp commented on src/app/(auth)/login/components/LoginForm.tsx
>          <div className="text-custom-purple text-sm font-medium">Login</div>
Reutilizar componente de Label

2024-07-19 16:32 UTC, herisonp commented on src/app/(auth)/login/components/LoginForm.tsx
> +        )}
Reutilizar componente de InputMessage

2024-07-19 20:36 UTC, Luzin7 commented on src/schemas/userLogin.ts
> +    .trim(),
Concordo totalmente! Vou resolver esse caso.

2024-07-23 16:59 UTC, herisonp requested changes
@Luzin7 Acho que você não fez uso dos componentes que eu mencionei. Reutiliza nossos componentes de Label e InputMessage. E se precisar estruturar o conjunto de Label, Input e InputMessage, a gente tem o InputControl que serve para agrupar esses 3 componentes. Da uma olhada em como o Diogo fez no PR dele.

Ficaria algo assim:

```JSX
<InputControl>
   <Label htmlFor="nome">Nome:</Label>
   <Input type="text" id="nome" name="nome" />
    {error ? <InputMessage message={error} />}
</InputControl>
```

Com exceção do Label, todos ficam dentro de Fields na pasta components.

2024-07-25 20:00 UTC, Luzin7 commented
> @Luzin7 Acho que você não fez uso dos componentes que eu mencionei. Reutiliza nossos componentes de Label e InputMessage. E se precisar estruturar o conjunto de Label, Input e InputMessage, a gente tem o InputControl que serve para agrupar esses 3 componentes. Da uma olhada em como o Diogo fez no PR dele.
> 
> Ficaria algo assim:
> 
> ```js
> <InputControl>
>    <Label htmlFor="nome">Nome:</Label>
>    <Input type="text" id="nome" name="nome" />
>     {error ? <InputMessage message={error} />}
> </InputControl>
> ```
> 
> Com exceção do Label, todos ficam dentro de Fields na pasta components.

Ah entendi agora, vou corrigir isso.

2024-07-27 04:39 UTC, herisonp requested changes
@Luzin7 agora ta certinho com o uso dos componentes! Deixei só mais um comentário. Mas é coisa rápida.

2024-07-27 04:39 UTC, herisonp commented on src/app/(auth)/login/components/LoginForm.tsx
> +        />
@Luzin7 ficou faltando só a propriedade de htmlFor para indicar a qual input a Label pertence. Faltou em todos os Labels.

2024-07-27 18:36 UTC, herisonp approved these changes
@Luzin7 Aprovado!!

2024-07-27 18:36 UTC, merged